name: Go Cross-Platform Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23.0']  # Updated to Go 1.23.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go-version }}-

    - name: Install dependencies
      run: go mod download

    - name: Debug Go Environment
      run: |
        echo "Go Environment Information"
        go env
        echo "Go Version"
        go version
        echo "Current Directory"
        pwd
        echo "Listing Files"
        ls -la
        echo "Checking go.mod"
        cat go.mod

    - name: Build for ${{ matrix.os }}
      run: |
        echo "Starting build for $RUNNER_OS..."
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          GOOS=linux GOARCH=amd64 go build -o builds/SkyeCraft-linux
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          GOOS=darwin GOARCH=amd64 go build -o builds/SkyeCraft-macOS
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          GOOS=windows GOARCH=amd64 go build -ldflags="-H windowsgui" -o builds/SkyeCraft.exe
        fi
        echo "Build completed for $RUNNER_OS."
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SkyeCraft
        path: builds/

    - name: Print build folder contents
      run: |
        echo "Listing contents of builds/ folder"
        ls -la builds/
